apiVersion: v1
appVersion: 1.1.2
description: Fast and Lightweight Log/Data Forwarder for Linux, BSD and OSX
home: http://fluentbit.io
icon: http://fluentbit.io/assets/img/logo1-default.png
keywords:
- logging
- monitoring
- fluent
- fluentd
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: eduardo@treasure-data.com
  name: edsiper
- email: hfernandez@mesosphere.com
  name: hectorj2f
name: fluent-bit
sources:
- http://fluentbit.io
version: 2.0.5
